name: github curl
on: push

jobs:
  curl:
    name: github curl
    steps:
      - run: |
        curl \
        --request GET \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'